version: '3.8'

services:
    symfony:
        build: symfony_config
        container_name: symfony_docker
        ports:
            - "1234:80"
        volumes:
            - ./symfony_config/vhosts:/etc/apache2/sites-enabled
            - ./symfony_project:/var/www/symfony_project
        restart: always
        networks:
            - dev

    db:
        image: mariadb:10.7.1
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - "8888:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    caddy:
        image: dunglas/mercure
        restart: unless-stopped
        container_name: mercure_docker
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            MERCURE_EXTRA_DIRECTIVES:
                cors_origins "http://localhost:3000"
                cors_origins "http://localhost:1234"
#                anonymous
        # Uncomment the following line to enable the development mode
#        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "9999:80"
            - "444:443"
#        volumes:
#            - caddy_data:/data
#            - caddy_config:/config
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
#    caddy_data:
#    caddy_config: